# Generated by Django 4.1.2 on 2023-01-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='photo_do_produto',
            field=models.ImageField(upload_to='Image/'),
        ),
    ]
