# Generated by Django 4.1.2 on 2023-03-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status_de_pagamento',
            field=models.CharField(blank=True, choices=[('pago', 'Pago'), ('pendente', 'Pendente')], max_length=15),
        ),
    ]
