# Generated by Django 4.1.2 on 2023-03-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedidos_status_de_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status_de_pagamento',
            field=models.CharField(blank=True, choices=[('pago', 'Pago'), ('pendente', 'Pendente')], max_length=15, null=True),
        ),
    ]
