# Generated by Django 4.1.2 on 2023-02-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedidos_usuario_alter_pedidos_status_de_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_da_mesa', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='numero_da_mesa',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='numero_da_mesa',
            field=models.ManyToManyField(blank=True, to='pedidos.tablenumber'),
        ),
    ]
