# Generated by Django 4.1.2 on 2023-03-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedidos_status_de_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='status_do_pedido',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('preparando', 'preparando'), ('pronto', 'Pronto')], max_length=15, null=True),
        ),
    ]
