# Generated by Django 4.1.2 on 2023-02-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_tablenumber_remove_pedidos_numero_da_mesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='numero_da_mesa',
            field=models.ManyToManyField(blank=True, related_name='mesa_numero', to='pedidos.tablenumber'),
        ),
    ]
