# Generated by Django 4.1.2 on 2023-03-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedidos_status_do_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status_do_pedido',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('preparando', 'Preparando'), ('pronto', 'Pronto')], max_length=15, null=True),
        ),
    ]
