# Generated by Django 4.1.2 on 2023-01-31 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvatarUser',
        ),
    ]
