# Generated by Django 4.1.2 on 2023-02-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_avataruser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avataruser',
            name='avatar',
            field=models.ImageField(default='Image/user_default.jpg', upload_to='Image/'),
        ),
    ]
